version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "site"  # Nome da definição de tarefa ECS
        LoadBalancerInfo:
          ContainerName: "site"  # Nome do contêiner definido na tarefa
          ContainerPort: 3000