version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 18
    commands:
    
  pre_build:
    on-failure: ABORT 
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 475476595453.dkr.ecr.us-east-1.amazonaws.com
    
  build:
    on-failure: ABORT 
    commands:
      - docker build -t site .
      - docker tag site:latest 475476595453.dkr.ecr.us-east-1.amazonaws.com/site:latest
    
  post_build:
    on-failure: ABORT 
    commands:
      - docker push 475476595453.dkr.ecr.us-east-1.amazonaws.com/site:latest

artifacts:
  files:
    - '**/*'