version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 475476595453.dkr.ecr.us-east-1.amazonaws.com
    
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t site .
      - docker tag site:latest 475476595453.dkr.ecr.us-east-1.amazonaws.com/site:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 475476595453.dkr.ecr.us-east-1.amazonaws.com/site:latest

#artifacts:
 # files:
 #   - '**/*'
